// medicationCode.js
const medicationList = [
    { name: "	Aspirin	", code: "	Aspirin	", description: "	Antiplatelet	" },
{ name: "	Abilify	", code: "	Aripiprazole	", description: "	Atypical Antipsychotic	" },
{ name: "	Actos	", code: "	Pioglitazone	", description: "	Thiazolidinedione (TZD)	" },
{ name: "	Adderall	", code: "	Amphetamine/dextroamphetamine	", description: "	Stimulant (ADHD)	" },
{ name: "	Advair	", code: "	Fluticasone/salmeterol	", description: "	Inhaled Corticosteroid + LABA	" },
{ name: "	Advil	", code: "	Ibuprofen	", description: "	NSAID	" },
{ name: "	Aggrenox	", code: "	Aspirin/Dipyridamole	", description: "	Antiplatelet	" },
{ name: "	Aldactone	", code: "	Spironolactone	", description: "	Potassium-Sparing Diuretic / Aldosterone Antagonist	" },
{ name: "	Altace	", code: "	Ramipril	", description: "	RAAS Inhibitor	" },
{ name: "	Amaryl	", code: "	Glimepiride	", description: "	Sulfonylurea	" },
{ name: "	Ambien	", code: "	Zolpidem	", description: "	Non-Benzodiazepine Hypnotic	" },
{ name: "	AndroGel	", code: "	Testosterone	", description: "	Androgen Replacement Therapy	" },
{ name: "	Aranesp	", code: "	Darbepoetin	", description: "	ESA	" },
{ name: "	Aricept	", code: "	Donepezil	", description: "	Acetylcholinesterase Inhibitor (Alzheimer’s)	" },
{ name: "	Arimidex	", code: "	Anastrozole	", description: "	Aromatase Inhibitor (Hormonal Therapy)	" },
{ name: "	Asacol-HD	", code: "	Mesalamine	", description: "	5-Aminosalicylate (Ulcerative Colitis)	" },
{ name: "	Ativan	", code: "	Lorazepam	", description: "	Benzodiazepine	" },
{ name: "	Atrovent	", code: "	Ipratropium	", description: "	Anticholinergic (Short-Acting)	" },
{ name: "	Avandia	", code: "	Rosiglitazone	", description: "	Thiazolidinedione (TZD)	" },
{ name: "	Benicar	", code: "	Olmesartan	", description: "	ARB	" },
{ name: "	Bentyl	", code: "	Dicyclomine	", description: "	Antispasmodic (Irritable Bowel Syndrome)	" },
{ name: "	Brilinta	", code: "	Ticagrelor	", description: "	Antiplatelet	" },
{ name: "	Bumex	", code: "	Bumetanide	", description: "	Loop Diuretic	" },
{ name: "	Byetta	", code: "	Exenatide	", description: "	GLP-1 Receptor Agonist	" },
{ name: "	Bystolic	", code: "	Nebivolol	", description: "	Beta Blocker	" },
{ name: "	Cardizem CD	", code: "	Diltiazem	", description: "	Calcium Channel Blocker	" },
{ name: "	Celebrex	", code: "	Celecoxib	", description: "	COX-2 Selective NSAID	" },
{ name: "	Celexa	", code: "	Citalopram	", description: "	SSRI	" },
{ name: "	Chantix	", code: "	Varenicline	", description: "	Partial Nicotinic Receptor Agonist (Smoking Cessation)	" },
{ name: "	Colace	", code: "	Docusate	", description: "	Stool Softener	" },
{ name: "	Combivent	", code: "	Albuterol/Ipratropium	", description: "	SABA + Anticholinergic	" },
{ name: "	Compazine	", code: "	Prochlorperazine	", description: "	Dopamine Antagonist (Antiemetic)	" },
{ name: "	Cordarone	", code: "	Amiodarone	", description: "	Antiarrhythmic	" },
{ name: "	Coreg	", code: "	Carvedilol	", description: "	Beta Blocker	" },
{ name: "	Coumadin	", code: "	Warfarin	", description: "	Vitamin K Antagonist (Anticoagulant)	" },
{ name: "	Cozaar	", code: "	Losartan	", description: "	ARB (Angiotensin II Receptor Blocker)	" },
{ name: "	Crestor	", code: "	Rosuvastatin	", description: "	Statin	" },
{ name: "	Cymbalta	", code: "	Duloxetine	", description: "	SNRI	" },
{ name: "	Deltasone	", code: "	Prednisone	", description: "	Corticosteroid	" },
{ name: "	Demadex	", code: "	Torsemide	", description: "	Loop Diuretic	" },
{ name: "	Depakote	", code: "	Valproic acid	", description: "	Anticonvulsant	" },
{ name: "	Desyrel	", code: "	Trazodone	", description: "	Serotonin Modulator	" },
{ name: "	Dexilant	", code: "	Dexlansoprazole	", description: "	PPI	" },
{ name: "	DiaBeta	", code: "	Glyburide	", description: "	Sulfonylurea	" },
{ name: "	Dilantin	", code: "	Phenytoin	", description: "	Anticonvulsant	" },
{ name: "	Dilaudid	", code: "	Hydromorphone	", description: "	Opioid Analgesic	" },
{ name: "	Diovan	", code: "	Valsartan	", description: "	ARB	" },
{ name: "	Dulcolax	", code: "	Bisacodyl	", description: "	Stimulant Laxative	" },
{ name: "	Duragesic	", code: "	Fentanyl	", description: "	Opioid Analgesic	" },
{ name: "	Effexor	", code: "	Venlafaxine	", description: "	Serotonin-Norepinephrine Reuptake Inhibitor (SNRI)	" },
{ name: "	Effient	", code: "	Prasugrel	", description: "	Antiplatelet	" },
{ name: "	Elavil	", code: "	Amitriptyline	", description: "	Tricyclic Antidepressant	" },
{ name: "	Eliquis	", code: "	Apixaban	", description: "	Factor Xa Inhibitor (NOAC)	" },
{ name: "	Epogen	", code: "	Epoetin alfa	", description: "	Erythropoiesis-Stimulating Agent (ESA)	" },
{ name: "	Fioricet	", code: "	Butalbital/APAP/caffeine	", description: "	Barbiturate Combination (Headache)	" },
{ name: "	Fiorinal	", code: "	Butalbital/aspirin/caffeine	", description: "	Barbiturate Combination (Headache)	" },
{ name: "	Flexeril	", code: "	Cyclobenzaprine	", description: "	Muscle Relaxant	" },
{ name: "	Flovent	", code: "	Fluticasone	", description: "	Inhaled Corticosteroid	" },
{ name: "	Foradil	", code: "	Formoterol	", description: "	Long-Acting Beta Agonist	" },
{ name: "	Geodon	", code: "	Ziprasidone	", description: "	Atypical Antipsychotic	" },
{ name: "	Glucophage	", code: "	Metformin	", description: "	Biguanide (Oral Antidiabetic)	" },
{ name: "	Glucotrol	", code: "	Glipizide	", description: "	Sulfonylurea	" },
{ name: "	Glucovance	", code: "	Glyburide/metformin	", description: "	Sulfonylurea + Biguanide	" },
{ name: "	GoLYTELY	", code: "	PEG 3350 with electrolytes	", description: "	Osmotic Laxative with Electrolytes	" },
{ name: "	HumaLOG	", code: "	Insulin lispro	", description: "	Rapid-Acting Insulin	" },
{ name: "	HumuLIN N	", code: "	Insulin NPH	", description: "	Intermediate-Acting Insulin	" },
{ name: "	Imdur	", code: "	Isosorbide mononitrate	", description: "	Nitrate (Antianginal)	" },
{ name: "	Imitrex	", code: "	Sumatriptan	", description: "	Serotonin (5-HT1) Agonist (Migraine)	" },
{ name: "	Imodium	", code: "	Loperamide	", description: "	Antidiarrheal	" },
{ name: "	Inderal	", code: "	Propranolol	", description: "	Beta Blocker	" },
{ name: "	Invokana	", code: "	Canagliflozin	", description: "	SGLT2 Inhibitor	" },
{ name: "	Janumet	", code: "	Sitagliptin/metformin	", description: "	DPP-4 Inhibitor + Biguanide	" },
{ name: "	Januvia	", code: "	Sitagliptin	", description: "	DPP-4 Inhibitor	" },
{ name: "	Keppra	", code: "	Levetiracetam	", description: "	Anticonvulsant	" },
{ name: "	Klonopin	", code: "	Clonazepam	", description: "	Benzodiazepine	" },
{ name: "	Klor-Con	", code: "	Potassium chloride	", description: "	Electrolyte Supplement	" },
{ name: "	Lamictal	", code: "	Lamotrigine	", description: "	Anticonvulsant	" },
{ name: "	Lanoxin	", code: "	Digoxin	", description: "	Cardiac Glycoside	" },
{ name: "	Lantus	", code: "	Insulin glargine	", description: "	Long-Acting Insulin	" },
{ name: "	Lasix	", code: "	Furosemide	", description: "	Loop Diuretic	" },
{ name: "	Levemir	", code: "	Insulin detemir	", description: "	Long-Acting Insulin	" },
{ name: "	Lexapro	", code: "	Escitalopram	", description: "	SSRI	" },
{ name: "	Lidoderm	", code: "	Lidocaine patch	", description: "	Topical Analgesic	" },
{ name: "	Lipitor	", code: "	Atorvastatin	", description: "	Statin	" },
{ name: "	Lomotil	", code: "	Diphenoxylate/atropine	", description: "	Antidiarrheal	" },
{ name: "	Lopid	", code: "	Gemfibrozil	", description: "	Fibric Acid Derivative	" },
{ name: "	Lopressor	", code: "	Metoprolol tartrate	", description: "	Beta Blocker	" },
{ name: "	Lotrel	", code: "	Amlodipine/benazepril	", description: "	Calcium Channel Blocker + ACE Inhibitor	" },
{ name: "	Lovaza	", code: "	Omega-3 Acid Ethyl Esters	", description: "	Antihyperlipidemic Agent	" },
{ name: "	Lovenox	", code: "	Enoxaparin	", description: "	Low Molecular Weight Heparin	" },
{ name: "	Lunesta	", code: "	Eszopiclone	", description: "	Non-Benzodiazepine Hypnotic	" },
{ name: "	Lyrica	", code: "	Pregabalin	", description: "	Anticonvulsant / Neuropathic Pain Agent	" },
{ name: "	Maxalt	", code: "	Rizatriptan	", description: "	Serotonin (5-HT1) Agonist (Migraine)	" },
{ name: "	Medrol	", code: "	Methylprednisolone	", description: "	Corticosteroid	" },
{ name: "	Micronor	", code: "	Norethindrone	", description: "	Progestin-Only Contraceptive	" },
{ name: "	Microzide	", code: "	Hydrochlorothiazide	", description: "	Thiazide Diuretic	" },
{ name: "	MiraLAX	", code: "	PEG 3350	", description: "	Osmotic Laxative	" },
{ name: "	Mobic	", code: "	Meloxicam	", description: "	NSAID	" },
{ name: "	MS Contin	", code: "	Morphine	", description: "	Opioid Analgesic	" },
{ name: "	Namenda XR	", code: "	Memantine	", description: "	NMDA Receptor Antagonist (Alzheimer’s)	" },
{ name: "	Naprosyn	", code: "	Naproxen	", description: "	NSAID	" },
{ name: "	Neurontin	", code: "	Gabapentin	", description: "	Anticonvulsant / Neuropathic Pain Agent	" },
{ name: "	Nexium	", code: "	Esomeprazole	", description: "	PPI	" },
{ name: "	Niaspan	", code: "	Niacin	", description: "	Antihyperlipidemic Agent	" },
{ name: "	Nicoderm CQ	", code: "	Nicotine Patch	", description: "	Smoking Cessation Aid	" },
{ name: "	Nitrostat	", code: "	Nitroglycerin	", description: "	Nitrate (Antianginal)	" },
{ name: "	Nolvadex	", code: "	Tamoxifen	", description: "	Selective Estrogen Receptor Modulator (SERM)	" },
{ name: "	Norco	", code: "	Hydrocodone/APAP	", description: "	Opioid Analgesic + APAP	" },
{ name: "	Norvasc	", code: "	Amlodipine	", description: "	Calcium Channel Blocker	" },
{ name: "	NovoLOG	", code: "	Insulin aspart	", description: "	Rapid-Acting Insulin	" },
{ name: "	NuvaRing	", code: "	Etonogestrel/ethinyl estradiol	", description: "	Vaginal Ring Contraceptive	" },
{ name: "	Ortho Evra	", code: "	Norelgestromin/ethinyl estradiol	", description: "	Transdermal Contraceptive Patch	" },
{ name: "	Oxycontin	", code: "	Oxycodone	", description: "	Opioid Analgesic	" },
{ name: "	Pamelor	", code: "	Nortriptyline	", description: "	Tricyclic Antidepressant	" },
{ name: "	Paxil	", code: "	Paroxetine	", description: "	SSRI	" },
{ name: "	Pepcid	", code: "	Famotidine	", description: "	Histamine H2 Receptor Antagonist	" },
{ name: "	Percocet	", code: "	Oxycodone/APAP	", description: "	Opioid Analgesic + APAP	" },
{ name: "	Phenergan	", code: "	Promethazine	", description: "	Antihistamine / Antiemetic	" },
{ name: "	Plavix	", code: "	Clopidogrel	", description: "	Antiplatelet	" },
{ name: "	Pradaxa	", code: "	Dabigatran	", description: "	Direct Thrombin Inhibitor (NOAC)	" },
{ name: "	Pravachol	", code: "	Pravastatin	", description: "	HMG-CoA Reductase Inhibitor (Statin)	" },
{ name: "	Premarin	", code: "	Conjugated estrogens	", description: "	Estrogen Replacement Therapy	" },
{ name: "	Prevacid	", code: "	Lansoprazole	", description: "	PPI	" },
{ name: "	Prilosec	", code: "	Omeprazole	", description: "	Proton Pump Inhibitor (PPI)	" },
{ name: "	Prinivil	", code: "	Lisinopril	", description: "	RAAS Inhibitor	" },
{ name: "	Prinzide	", code: "	Lisinopril/hydrochlorothiazide	", description: "	RAAS Inhibitor + Diuretic	" },
{ name: "	Pristiq	", code: "	Desvenlafaxine	", description: "	SNRI	" },
{ name: "	Procardia XL	", code: "	Nifedipine XL	", description: "	Calcium Channel Blocker	" },
{ name: "	Protonix	", code: "	Pantoprazole	", description: "	PPI	" },
{ name: "	Provigil	", code: "	Modafinil	", description: "	Wakefulness-Promoting Agent	" },
{ name: "	Prozac	", code: "	Fluoxetine	", description: "	Selective Serotonin Reuptake Inhibitor (SSRI)	" },
{ name: "	Pulmicort	", code: "	Budesonide	", description: "	Inhaled Corticosteroid	" },
{ name: "	Ranexa	", code: "	Ranolazine	", description: "	Antianginal Agent	" },
{ name: "	Reglan	", code: "	Metoclopramide	", description: "	Prokinetic / Dopamine Antagonist (Antiemetic)	" },
{ name: "	Relpax	", code: "	Eletriptan	", description: "	Serotonin (5-HT1) Agonist (Migraine)	" },
{ name: "	Remeron	", code: "	Mirtazapine	", description: "	Tetracyclic Antidepressant	" },
{ name: "	Renvela	", code: "	Sevelamer carbonate	", description: "	Phosphate Binder	" },
{ name: "	Risperdal	", code: "	Risperidone	", description: "	Atypical Antipsychotic	" },
{ name: "	Ritalin	", code: "	Methylphenidate	", description: "	Stimulant (ADHD)	" },
{ name: "	Senokot	", code: "	Senna	", description: "	Stimulant Laxative	" },
{ name: "	Senokot-S	", code: "	Senna/docusate	", description: "	Stimulant Laxative + Stool Softener	" },
{ name: "	Sensipar	", code: "	Cinacalcet	", description: "	Calcimimetic	" },
{ name: "	Serevent	", code: "	Salmeterol	", description: "	Long-Acting Beta Agonist	" },
{ name: "	Seroquel	", code: "	Quetiapine	", description: "	Atypical Antipsychotic	" },
{ name: "	Singulair	", code: "	Montelukast	", description: "	Leukotriene Receptor Antagonist	" },
{ name: "	Soma	", code: "	Carisoprodol	", description: "	Muscle Relaxant	" },
{ name: "	Spiriva	", code: "	Tiotropium	", description: "	Anticholinergic (Long-Acting)	" },
{ name: "	Sprintec	", code: "	Norgestimate/ethinyl estradiol	", description: "	Combined Oral Contraceptive	" },
{ name: "	Strattera	", code: "	Atomoxetine	", description: "	Selective Norepinephrine Reuptake Inhibitor (ADHD)	" },
{ name: "	Suboxone	", code: "	Buprenorphine/naloxone	", description: "	Opioid Partial Agonist/Antagonist	" },
{ name: "	Symbicort	", code: "	Budesonide/formoterol	", description: "	Inhaled Corticosteroid + LABA	" },
{ name: "	Synthroid	", code: "	Levothyroxine	", description: "	Thyroid Hormone	" },
{ name: "	Tegretol	", code: "	Carbamazepine	", description: "	Anticonvulsant	" },
{ name: "	Tenormin	", code: "	Atenolol	", description: "	Beta Blocker	" },
{ name: "	Toprol XL	", code: "	Metoprolol succinate	", description: "	Beta Blocker	" },
{ name: "	Tricor	", code: "	Fenofibrate	", description: "	Fibric Acid Derivative	" },
{ name: "	Trileptal	", code: "	Oxcarbazepine	", description: "	Anticonvulsant	" },
{ name: "	Tylenol #3	", code: "	Codeine/APAP	", description: "	Opioid Analgesic + APAP	" },
{ name: "	Ultram	", code: "	Tramadol	", description: "	Opioid Analgesic	" },
{ name: "	Valium	", code: "	Diazepam	", description: "	Benzodiazepine	" },
{ name: "	Vasotec	", code: "	Enalapril	", description: "	RAAS Inhibitor	" },
{ name: "	Ventolin	", code: "	Albuterol	", description: "	Short-Acting Beta Agonist (SABA)	" },
{ name: "	Voltaren	", code: "	Diclofenac	", description: "	NSAID	" },
{ name: "	Vytorin	", code: "	Simvastatin/ezetimibe	", description: "	Statin + Cholesterol Absorption Inhibitor	" },
{ name: "	Vyvanse	", code: "	Lisdexamfetamine	", description: "	Stimulant (ADHD)	" },
{ name: "	Welchol	", code: "	Colesevelam	", description: "	Bile Acid Sequestrant	" },
{ name: "	Wellbutrin	", code: "	Bupropion	", description: "	Norepinephrine-Dopamine Reuptake Inhibitor (NDRI)	" },
{ name: "	Xanax	", code: "	Alprazolam	", description: "	Benzodiazepine	" },
{ name: "	Xarelto	", code: "	Rivaroxaban	", description: "	Factor Xa Inhibitor (NOAC)	" },
{ name: "	Xopenex	", code: "	Levalbuterol	", description: "	SABA	" },
{ name: "	Yaz	", code: "	Drospirenone/ethinyl estradiol	", description: "	Combined Oral Contraceptive	" },
{ name: "	Zantac	", code: "	Ranitidine	", description: "	H2 Receptor Antagonist	" },
{ name: "	Zaroxolyn	", code: "	Metolazone	", description: "	Thiazide-like Diuretic	" },
{ name: "	Zetia	", code: "	Ezetimibe	", description: "	Cholesterol Absorption Inhibitor	" },
{ name: "	Zocor	", code: "	Simvastatin	", description: "	Statin	" },
{ name: "	Zofran	", code: "	Ondansetron	", description: "	5-HT3 Antagonist (Antiemetic)	" },
{ name: "	Zoloft	", code: "	Sertraline	", description: "	SSRI	" },
{ name: "	Zyprexa	", code: "	Olanzapine	", description: "	Atypical Antipsychotic	" }
];


function addMedication(name, code) {
    medicationList.push({ name, code });
    updateMedicationButtons();
}

function addhere() {
    // Show the Add Medication panel
    document.getElementById("addMedPanel").style.display = "flex";
}

function closeAddPanel() {
    document.getElementById("addMedPanel").style.display = "none";
}

function saveNewMedication() {
    const name = document.getElementById("newMedName").value.trim();
    const code = document.getElementById("newMedCode").value.trim();
    const description = document.getElementById("newMedDesc").value.trim();

    if (!name || !code || !description) {
        alert("Please fill in all fields.");
        return;
    }

    medicationList.push({ name, code, description });
    localStorage.setItem("medicationList", JSON.stringify(medicationList));
    updateMedicationButtons();
    closeAddPanel();
    
    // Optionally clear form fields
    document.getElementById("newMedName").value = "";
    document.getElementById("newMedCode").value = "";
    document.getElementById("newMedDesc").value = "";
}
